### ISSUE TITLE
Update  sources as its loading the wrong library

### ISSUE THREAD

**Issue by p10tyr** [tspence/docker-examples#2]
https://github.com/tspence/docker-examples/blob/086fa3539045e60c747a27c3c16329a380746201/sqlserver-fulltext/Dockerfile#L14

this needs to be updated to 
`...ubuntu/22.04/mssql-server-2022...`

or you will get this error
```
/opt/mssql/bin/sqlservr: error while loading shared libraries: libssl.so.1.1: wrong ELF class: ELFCLASS32
```

**Comment by tspence** [comment]
Thanks!  I've updated my dockerfile.
